version: "2"
services:
  bartsign:
    build: ./bart
    restart: always
    privileged: true
    devices:
      - "/dev/mem:/dev/mem"

  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    privileged: true
    labels:
      io.balena.features.dbus: "1"
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
